// LSIG Runtime Agent — userspace Go orchestrator for the eBPF uprobe program.
//
// Responsibilities:
//   1. Load and pin the eBPF object (uprobe.bpf.o)
//   2. Discover target PIDs from /proc and attach uprobes to their binaries
//   3. Read call events from the perf ring buffer
//   4. Symbolize instruction pointers → (function name, source file, line)
//   5. Aggregate into 60-second windows via CallAggregator
//   6. Emit RuntimeCallEvent structs to Kafka
//
// Runs as a Kubernetes DaemonSet with hostPID:true and CAP_SYS_PTRACE.
//
// Usage:
//
//	runtime-agent \
//	  --bpf-object /opt/lsig/uprobe.bpf.o \
//	  --kafka-brokers kafka:9092 \
//	  --kafka-topic runtime_calls \
//	  --repo-root /src
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/rlimit"

	// Prometheus metrics
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// ─── CLI flags ────────────────────────────────────────────────────────────────

var (
	flagBPFObject    = flag.String("bpf-object", "/opt/lsig/uprobe.bpf.o", "Path to compiled eBPF object file")
	flagKafkaBrokers = flag.String("kafka-brokers", "localhost:9092", "Comma-separated Kafka broker list")
	flagKafkaTopic   = flag.String("kafka-topic", "runtime_calls", "Kafka topic for runtime call events")
	flagRepoRoot     = flag.String("repo-root", "", "Repo source root for stripping absolute paths")
	flagMetricsAddr  = flag.String("metrics-addr", ":9091", "Prometheus metrics listen address")
	flagPerfPages    = flag.Int("perf-pages", 64, "Number of perf ring buffer pages (must be power of 2)")
	flagServiceEnv   = flag.String("service-env", "LSIG_SERVICE", "Env var name injected into target containers to identify service name")
)

// ─── Prometheus metrics ───────────────────────────────────────────────────────

var (
	metricEventsReceived = promauto.NewCounter(prometheus.CounterOpts{
		Name: "lsig_runtime_agent_events_total",
		Help: "Total eBPF call events received from perf buffer",
	})
	metricEventsDropped = promauto.NewCounter(prometheus.CounterOpts{
		Name: "lsig_runtime_agent_events_dropped_total",
		Help: "eBPF events dropped due to full perf buffer",
	})
	metricSymbolizeErrors = promauto.NewCounter(prometheus.CounterOpts{
		Name: "lsig_runtime_agent_symbolize_errors_total",
		Help: "Failed symbol resolutions",
	})
	metricKafkaEmitted = promauto.NewCounter(prometheus.CounterOpts{
		Name: "lsig_runtime_agent_kafka_events_total",
		Help: "Aggregated events emitted to Kafka",
	})
	metricActiveProbes = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "lsig_runtime_agent_active_probes",
		Help: "Number of currently attached uprobes",
	})
)

// ─── eBPF object layout (mirrors uprobe.bpf.c maps/programs) ─────────────────

// bpfObjects holds the loaded eBPF programs and maps.
// Generated by bpf2go from uprobe.bpf.c — replicated here for clarity.
type bpfObjects struct {
	// Programs
	UprobeEntry  *ebpf.Program `ebpf:"uprobe_entry"`
	UprobeReturn *ebpf.Program `ebpf:"uprobe_return"`

	// Maps
	CallEvents *ebpf.Map `ebpf:"call_events"`
	Scratch    *ebpf.Map `ebpf:"scratch"`
	EntryTimes *ebpf.Map `ebpf:"entry_times"`
	PidFilter  *ebpf.Map `ebpf:"pid_filter"`
}

// bpfCallEvent mirrors the C struct call_event.
type bpfCallEvent struct {
	TimestampNs uint64
	Pid         uint32
	Tgid        uint32
	FuncIP      uint64
	CallerIP    uint64
	CPUTimeNs   uint64
	Comm        [16]byte
	IsReturn    uint8
	_           [7]byte // alignment padding to match C struct
}

// ─── Process / binary discovery ───────────────────────────────────────────────

type processInfo struct {
	pid     uint32
	binary  string
	service string
}

// discoverProcesses reads /proc to find all running processes and their binaries.
func discoverProcesses() []processInfo {
	entries, err := filepath.Glob("/proc/[0-9]*/exe")
	if err != nil {
		return nil
	}

	var procs []processInfo
	for _, exe := range entries {
		var pidU uint32
		if _, err := parsePIDFromPath(exe, &pidU); err != nil {
			continue
		}
		target, err := os.Readlink(exe)
		if err != nil {
			continue
		}
		procs = append(procs, processInfo{
			pid:     pidU,
			binary:  target,
			service: serviceNameForPID(pidU),
		})
	}
	return procs
}

// parsePIDFromPath extracts the PID integer from a /proc/<pid>/exe path.
func parsePIDFromPath(exePath string, out *uint32) (int, error) {
	var n int
	_, err := fmt.Sscanf(filepath.Dir(exePath), "/proc/%d", &n)
	if err != nil {
		return 0, err
	}
	*out = uint32(n)
	return n, nil
}

// binaryForPID returns the executable path for a given PID by reading /proc/<pid>/exe.
func binaryForPID(pid uint32) (string, error) {
	return os.Readlink(fmt.Sprintf("/proc/%d/exe", pid))
}

// serviceNameForPID attempts to identify the service name for a process by reading:
//  1. /proc/<pid>/environ for LSIG_SERVICE env var (injected by k8s downward API)
//  2. Falls back to the binary basename without extension
func serviceNameForPID(pid uint32) string {
	envFile := fmt.Sprintf("/proc/%d/environ", pid)
	data, err := os.ReadFile(envFile)
	if err == nil {
		// environ entries are NUL-separated
		prefix := *flagServiceEnv + "="
		for _, entry := range strings.Split(string(data), "\x00") {
			if strings.HasPrefix(entry, prefix) {
				return strings.TrimPrefix(entry, prefix)
			}
		}
	}

	// Fallback: read /proc/<pid>/exe and use basename
	if exe, err := os.Readlink(fmt.Sprintf("/proc/%d/exe", pid)); err == nil {
		base := filepath.Base(exe)
		// Strip common suffixes: .bin, .out, version suffixes
		base = strings.TrimSuffix(base, filepath.Ext(base))
		return base
	}
	return fmt.Sprintf("pid-%d", pid)
}

// ─── Main ─────────────────────────────────────────────────────────────────────

func main() {
	flag.Parse()

	os.Setenv("KAFKA_BROKERS", *flagKafkaBrokers)
	os.Setenv("KAFKA_TOPIC", *flagKafkaTopic)

	log.Printf("LSIG Runtime Agent starting — bpf=%s kafka=%s topic=%s",
		*flagBPFObject, *flagKafkaBrokers, *flagKafkaTopic)

	// Remove rlimit on locked memory so eBPF maps can be pinned
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("rlimit.RemoveMemlock: %v", err)
	}

	// Load eBPF object
	spec, err := ebpf.LoadCollectionSpec(*flagBPFObject)
	if err != nil {
		log.Fatalf("LoadCollectionSpec %s: %v", *flagBPFObject, err)
	}

	var objs bpfObjects
	if err := spec.LoadAndAssign(&objs, nil); err != nil {
		var ve *ebpf.VerifierError
		if errors.As(err, &ve) {
			log.Fatalf("BPF verifier error: %+v", ve)
		}
		log.Fatalf("LoadAndAssign: %v", err)
	}
	defer objs.UprobeEntry.Close()
	defer objs.UprobeReturn.Close()
	defer objs.CallEvents.Close()

	// Perf reader
	rd, err := perf.NewReader(objs.CallEvents, *flagPerfPages*os.Getpagesize())
	if err != nil {
		log.Fatalf("perf.NewReader: %v", err)
	}
	defer rd.Close()

	// Symbolizer + Kafka producer + aggregator
	sym, err := NewSymbolizer()
	if err != nil {
		log.Fatalf("NewSymbolizer: %v", err)
	}

	producer, err := NewKafkaProducer()
	if err != nil {
		log.Fatalf("NewKafkaProducer: %v", err)
	}
	defer producer.Close()

	agg := NewCallAggregator(producer)

	// Context wired to OS signals
	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	// Start Kafka flush loop
	go agg.RunFlushLoop(ctx)

	// Attach uprobes to discovered processes
	var links []link.Link
	procs := discoverProcesses()
	log.Printf("Discovered %d processes to instrument", len(procs))

	for _, proc := range procs {
		ex, err := link.OpenExecutable(proc.binary)
		if err != nil {
			log.Printf("OpenExecutable pid=%d binary=%s: %v", proc.pid, proc.binary, err)
			continue
		}

		// Attach to the executable entry point symbol "main" by default.
		// Production deployments scope this to LSIG_SYMBOL_ALLOWLIST.
		entryLink, err := ex.Uprobe("main", objs.UprobeEntry, nil)
		if err != nil {
			log.Printf("Uprobe attach pid=%d: %v", proc.pid, err)
			continue
		}
		retLink, err := ex.Uretprobe("main", objs.UprobeReturn, nil)
		if err != nil {
			entryLink.Close()
			log.Printf("Uretprobe attach pid=%d: %v", proc.pid, err)
			continue
		}
		links = append(links, entryLink, retLink)
		metricActiveProbes.Add(2)
	}
	defer func() {
		for _, l := range links {
			l.Close()
		}
	}()

	// Start Prometheus metrics server
	go func() {
		mux := http.NewServeMux()
		mux.Handle("/metrics", promhttp.Handler())
		log.Printf("Metrics server on %s", *flagMetricsAddr)
		if err := http.ListenAndServe(*flagMetricsAddr, mux); err != nil {
			log.Printf("metrics server: %v", err)
		}
	}()

	log.Printf("Runtime agent ready — reading perf events")

	// ─── Event loop ──────────────────────────────────────────────────────────
	var rawEvent bpfCallEvent
	for {
		select {
		case <-ctx.Done():
			log.Println("Shutdown signal received")
			return
		default:
		}

		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, perf.ErrClosed) {
				return
			}
			log.Printf("perf read error: %v", err)
			continue
		}

		if record.LostSamples > 0 {
			metricEventsDropped.Add(float64(record.LostSamples))
		}

		if err := decodeEvent(record.RawSample, &rawEvent); err != nil {
			continue
		}
		metricEventsReceived.Inc()

		// Only process entry events for call counting
		if rawEvent.IsReturn != 0 {
			continue
		}

		pid := rawEvent.Pid
		binary, err := binaryForPID(pid)
		if err != nil {
			continue
		}

		funcSym, err := sym.Resolve(binary, rawEvent.FuncIP)
		if err != nil {
			metricSymbolizeErrors.Inc()
			continue
		}
		callerSym, _ := sym.Resolve(binary, rawEvent.CallerIP)

		sourceFile := funcSym.File
		if *flagRepoRoot != "" {
			sourceFile = StripRepoRoot(funcSym.File, *flagRepoRoot)
		}

		service := serviceNameForPID(pid)

		agg.Record(
			service,
			funcSym.Name,
			sourceFile,
			funcSym.Line,
			callerSym.Name,
			binary,
			pid,
		)
	}
}

// decodeEvent deserialises a raw perf record into bpfCallEvent.
// Uses unsafe pointer arithmetic to match the C struct layout without cgo overhead.
func decodeEvent(raw []byte, ev *bpfCallEvent) error {
	const minSize = 57 // offsetof(IsReturn) + 1 byte
	if len(raw) < minSize {
		return fmt.Errorf("short perf record: %d bytes (need %d)", len(raw), minSize)
	}
	ev.TimestampNs = *(*uint64)(unsafe.Pointer(&raw[0]))
	ev.Pid = *(*uint32)(unsafe.Pointer(&raw[8]))
	ev.Tgid = *(*uint32)(unsafe.Pointer(&raw[12]))
	ev.FuncIP = *(*uint64)(unsafe.Pointer(&raw[16]))
	ev.CallerIP = *(*uint64)(unsafe.Pointer(&raw[24]))
	ev.CPUTimeNs = *(*uint64)(unsafe.Pointer(&raw[32]))
	copy(ev.Comm[:], raw[40:56])
	ev.IsReturn = raw[56]
	return nil
}
