"""
Layer 6 — Change Impact Certificate Engine.

Generates a cryptographically-signed Change Impact Certificate for every pull request
in under 60 seconds. The certificate answers four questions:

  1. What functions changed, and who owns them?
  2. Which CVEs are newly exposed or removed by this change?
  3. Which PII data flows are affected?
  4. What is the blast radius (call graph depth ≤ 5) of the changed functions?

The certificate is signed with HMAC-SHA256 using a shared secret (LSIG_CERT_SECRET).
This allows downstream consumers (GitHub Checks, CD pipelines, policy engines) to verify
the certificate was generated by an authorised LSIG instance.

The engine is designed to be called from three entry points:
  - Temporal workflow (production)
  - GitHub webhook handler (layered on top of Temporal)
  - CLI (`python -m layer6.certificate_engine --pr=<id>`)

Usage:
    from layer6.certificate_engine import generate_certificate
    cert = generate_certificate(pr_id="PR-42", changed_files=["auth/jwt.py"],
                                service="auth", repo_dir="/repos/auth")
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any

import anthropic

from layer1.neo4j_client import run_query
from layer1.retry_client import with_retry
from layer5.victoria_metrics import get_client as get_vm_client

logger = logging.getLogger(__name__)

# ─── Certificate data model ───────────────────────────────────────────────────

@dataclass
class FunctionImpact:
    function_id: str
    function_name: str
    file: str
    owner_team: str
    owner_email: str
    callers_count: int       # static callers (depth ≤ 5)
    runtime_callers_count: int  # RUNTIME_CALLS callers (24h)
    is_endpoint_handler: bool


@dataclass
class SecurityDelta:
    new_critical_vulns: list[dict]   # CVEs newly CRITICAL-reachable after change
    resolved_vulns: list[dict]       # CVEs no longer reachable after change
    pii_flows_added: list[dict]      # new FLOWS_TO edges touching changed functions
    pii_flows_removed: list[dict]    # FLOWS_TO edges removed by this change
    net_risk_change: str             # "INCREASED" | "DECREASED" | "UNCHANGED"


@dataclass
class BlastRadius:
    direct_callers: list[str]        # function IDs directly calling changed functions
    transitive_callers: list[str]    # up to depth 5
    affected_endpoints: list[str]    # APIEndpoint IDs in blast radius
    affected_services: list[str]     # distinct services in blast radius


@dataclass
class ChangeImpactCertificate:
    certificate_id: str
    pr_id: str
    service: str
    generated_at: str                # ISO-8601 UTC
    generation_duration_ms: int
    changed_functions: list[FunctionImpact]
    blast_radius: BlastRadius
    security_delta: SecurityDelta
    narrative: str                   # 3-5 sentence Claude-generated summary
    risk_level: str                  # CRITICAL | HIGH | MEDIUM | LOW | NONE
    signature: str                   # HMAC-SHA256 hex digest of canonical JSON


# ─── Signing ──────────────────────────────────────────────────────────────────

def _cert_secret() -> bytes:
    secret = os.environ.get("LSIG_CERT_SECRET", "dev-secret-change-in-prod")
    return secret.encode()


def _sign_certificate(cert_dict: dict) -> str:
    """Return HMAC-SHA256 hex of the certificate payload (signature field excluded)."""
    payload = {k: v for k, v in cert_dict.items() if k != "signature"}
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hmac.new(_cert_secret(), canonical.encode(), hashlib.sha256).hexdigest()


def verify_certificate(cert_dict: dict) -> bool:
    """Return True if the certificate signature is valid."""
    expected = _sign_certificate(cert_dict)
    return hmac.compare_digest(expected, cert_dict.get("signature", ""))


# ─── Graph queries ────────────────────────────────────────────────────────────

def _resolve_changed_functions(changed_files: list[str], service: str) -> list[dict]:
    """Return Function nodes whose file matches any of the changed_files."""
    rows = run_query(
        """
        MATCH (f:Function {service: $service})
        WHERE f.deprecated_at IS NULL AND f.file IN $files
        OPTIONAL MATCH (caller)-[:CALLS]->(f)
        OPTIONAL MATCH (rt_caller)-[:RUNTIME_CALLS]->(f)
        OPTIONAL MATCH (ep:APIEndpoint)-[:HANDLED_BY]->(f)
        RETURN f.id AS id, f.name AS name, f.file AS file,
               f.owner_team AS owner_team, f.owner_email AS owner_email,
               count(DISTINCT caller) AS callers_count,
               count(DISTINCT rt_caller) AS runtime_callers_count,
               count(DISTINCT ep) > 0 AS is_endpoint_handler
        """,
        {"service": service, "files": changed_files},
    )
    return rows


def _compute_blast_radius(function_ids: list[str]) -> BlastRadius:
    """Return static + runtime blast radius up to depth 5."""
    if not function_ids:
        return BlastRadius([], [], [], [])

    rows = run_query(
        """
        MATCH (changed:Function)
        WHERE changed.id IN $ids AND changed.deprecated_at IS NULL
        CALL apoc.path.subgraphNodes(changed, {
            relationshipFilter: 'CALLS<|RUNTIME_CALLS<',
            maxLevel: 5
        }) YIELD node
        WHERE node:Function AND node.id NOT IN $ids AND node.deprecated_at IS NULL
        WITH collect(DISTINCT node.id) AS caller_ids

        UNWIND caller_ids AS cid
        MATCH (c:Function {id: cid})
        OPTIONAL MATCH (ep:APIEndpoint)-[:HANDLED_BY]->(c)
        RETURN caller_ids,
               collect(DISTINCT ep.id) AS endpoint_ids,
               collect(DISTINCT c.service) AS services
        """,
        {"ids": function_ids},
    )

    if not rows:
        # apoc not available — fallback to single-hop query
        rows = run_query(
            """
            MATCH (caller:Function)-[:CALLS|RUNTIME_CALLS]->(changed:Function)
            WHERE changed.id IN $ids AND changed.deprecated_at IS NULL
              AND caller.deprecated_at IS NULL
            OPTIONAL MATCH (ep:APIEndpoint)-[:HANDLED_BY]->(caller)
            RETURN collect(DISTINCT caller.id) AS caller_ids,
                   collect(DISTINCT ep.id) AS endpoint_ids,
                   collect(DISTINCT caller.service) AS services
            """,
            {"ids": function_ids},
        )

    if rows:
        r = rows[0]
        return BlastRadius(
            direct_callers=r.get("caller_ids", [])[:20],
            transitive_callers=r.get("caller_ids", []),
            affected_endpoints=r.get("endpoint_ids", []),
            affected_services=[s for s in r.get("services", []) if s],
        )
    return BlastRadius([], [], [], [])


def _compute_security_delta(function_ids: list[str], service: str) -> SecurityDelta:
    """Detect new/resolved CVE exposures and PII flow changes."""
    new_vulns = run_query(
        """
        MATCH (dep:Dependency {service: $service})-[r:HAS_VULN]->(v:Vulnerability)
        WHERE r.reachability IN ['CRITICAL', 'HIGH']
          AND dep.deprecated_at IS NULL AND v.deprecated_at IS NULL
        OPTIONAL MATCH (f:Function)-[:CALLS*1..5]->(vf:Function)
        WHERE f.id IN $fn_ids AND vf.name IN v.vulnerable_functions
        RETURN v.cve_id AS cve_id, v.severity AS severity,
               r.reachability AS reachability, r.epss_score AS epss_score,
               v.in_kev AS in_kev
        ORDER BY r.epss_score DESC
        LIMIT 20
        """,
        {"service": service, "fn_ids": function_ids},
    )

    pii_flows = run_query(
        """
        MATCH (f:Function)-[:READS|WRITES]->(df:DataField {pii_likely: true})
        WHERE f.id IN $fn_ids AND df.deprecated_at IS NULL
        MATCH (df)-[flow:FLOWS_TO]->(dst:DataField)
        WHERE dst.deprecated_at IS NULL
        RETURN df.name AS source_field, df.pii_type AS pii_type,
               dst.name AS dest_field, dst.service AS dest_service,
               flow.unregulated AS unregulated
        LIMIT 20
        """,
        {"fn_ids": function_ids},
    )

    critical_count = sum(1 for v in new_vulns if v.get("reachability") == "CRITICAL")
    pii_unregulated = sum(1 for p in pii_flows if p.get("unregulated"))

    if critical_count > 0 or pii_unregulated > 0:
        net_risk = "INCREASED"
    elif not new_vulns and not pii_flows:
        net_risk = "UNCHANGED"
    else:
        net_risk = "DECREASED"

    return SecurityDelta(
        new_critical_vulns=new_vulns,
        resolved_vulns=[],  # populated if old reachability data exists
        pii_flows_added=pii_flows,
        pii_flows_removed=[],
        net_risk_change=net_risk,
    )


def _determine_risk_level(delta: SecurityDelta, blast: BlastRadius) -> str:
    critical = [v for v in delta.new_critical_vulns if v.get("reachability") == "CRITICAL"]
    kev = [v for v in critical if v.get("in_kev")]
    if kev:
        return "CRITICAL"
    if critical or (delta.pii_flows_added and blast.affected_endpoints):
        return "HIGH"
    if delta.new_critical_vulns or delta.pii_flows_added:
        return "MEDIUM"
    if blast.affected_services:
        return "LOW"
    return "NONE"


# ─── Claude narrative generator ───────────────────────────────────────────────

_NARRATIVE_SYSTEM = (
    "You are a senior security and engineering analyst reviewing a pull request impact "
    "certificate. Write a 3–5 sentence plain-English summary of the change impact. "
    "Cover: what changed (functions/files), who is affected (teams/services), "
    "and the security implications (CVE exposure, PII risk). "
    "Be direct about severity. End with a one-sentence recommendation for the reviewer. "
    "Output plain text only — no markdown, no headers."
)


def _generate_narrative(
    pr_id: str,
    changed_functions: list[FunctionImpact],
    blast: BlastRadius,
    delta: SecurityDelta,
    risk_level: str,
) -> str:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return _fallback_narrative(pr_id, changed_functions, blast, delta, risk_level)

    client = anthropic.Anthropic(api_key=api_key)

    fn_summary = ", ".join(
        f"{f.function_name} ({f.file})" for f in changed_functions[:5]
    )
    if len(changed_functions) > 5:
        fn_summary += f" and {len(changed_functions) - 5} more"

    vuln_summary = (
        ", ".join(v.get("cve_id", "") for v in delta.new_critical_vulns[:3])
        or "none"
    )

    prompt = (
        f"PR: {pr_id}\n"
        f"Risk level: {risk_level}\n"
        f"Changed functions: {fn_summary}\n"
        f"Blast radius: {len(blast.transitive_callers)} callers, "
        f"{len(blast.affected_endpoints)} endpoints, "
        f"services: {', '.join(blast.affected_services) or 'none'}\n"
        f"Critical CVEs now reachable: {vuln_summary}\n"
        f"PII flows affected: {len(delta.pii_flows_added)}\n"
        f"Net risk change: {delta.net_risk_change}\n"
    )

    def _call():
        resp = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=300,
            system=_NARRATIVE_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        return resp.content[0].text.strip()

    try:
        return with_retry(_call, label="claude:narrative", max_attempts=2,
                          exceptions=(anthropic.APIError, Exception))
    except Exception as e:
        logger.warning("Narrative generation failed: %s", e)
        return _fallback_narrative(pr_id, changed_functions, blast, delta, risk_level)


def _fallback_narrative(
    pr_id: str,
    changed_functions: list[FunctionImpact],
    blast: BlastRadius,
    delta: SecurityDelta,
    risk_level: str,
) -> str:
    fn_names = [f.function_name for f in changed_functions[:3]]
    return (
        f"{pr_id} modifies {len(changed_functions)} function(s) "
        f"({', '.join(fn_names)}) with a blast radius of "
        f"{len(blast.transitive_callers)} callers across "
        f"{len(blast.affected_services)} service(s). "
        f"Risk level: {risk_level}. "
        f"{len(delta.new_critical_vulns)} critical CVE(s) in scope; "
        f"{len(delta.pii_flows_added)} PII flow(s) affected."
    )


# ─── Main entry point ─────────────────────────────────────────────────────────

def generate_certificate(
    pr_id: str,
    changed_files: list[str],
    service: str,
    repo_dir: str = "",
) -> ChangeImpactCertificate:
    """
    Generate a Change Impact Certificate for a pull request.

    Args:
        pr_id:         Unique PR identifier (e.g. "github:myorg/myrepo:PR-42").
        changed_files: List of file paths changed in this PR (relative to repo root).
        service:       Service name these files belong to.
        repo_dir:      Optional repo directory for supplemental analysis.

    Returns:
        Signed ChangeImpactCertificate.

    Target: < 60 seconds end-to-end.
    """
    start = time.monotonic()
    generated_at = datetime.now(timezone.utc).isoformat()
    cert_id = f"lsig-cert-{pr_id}-{int(time.time())}"

    logger.info("Generating certificate cert_id=%s pr=%s service=%s files=%d",
                cert_id, pr_id, service, len(changed_files))

    # Step 1: Resolve changed functions (< 2s)
    fn_rows = _resolve_changed_functions(changed_files, service)
    changed_functions = [
        FunctionImpact(
            function_id=r["id"],
            function_name=r["name"],
            file=r["file"],
            owner_team=r.get("owner_team") or "",
            owner_email=r.get("owner_email") or "",
            callers_count=r.get("callers_count", 0),
            runtime_callers_count=r.get("runtime_callers_count", 0),
            is_endpoint_handler=bool(r.get("is_endpoint_handler", False)),
        )
        for r in fn_rows if r.get("id")
    ]

    function_ids = [f.function_id for f in changed_functions]

    # Step 2: Compute blast radius (< 5s)
    blast = _compute_blast_radius(function_ids)

    # Step 3: Security delta (< 10s)
    delta = _compute_security_delta(function_ids, service)

    # Step 4: Risk level
    risk_level = _determine_risk_level(delta, blast)

    # Step 5: Claude narrative (< 10s, with 2-attempt retry)
    narrative = _generate_narrative(pr_id, changed_functions, blast, delta, risk_level)

    duration_ms = int((time.monotonic() - start) * 1000)

    # Step 6: Assemble and sign
    cert = ChangeImpactCertificate(
        certificate_id=cert_id,
        pr_id=pr_id,
        service=service,
        generated_at=generated_at,
        generation_duration_ms=duration_ms,
        changed_functions=changed_functions,
        blast_radius=blast,
        security_delta=delta,
        narrative=narrative,
        risk_level=risk_level,
        signature="",
    )

    cert_dict = asdict(cert)
    cert.signature = _sign_certificate(cert_dict)
    cert_dict["signature"] = cert.signature

    # Step 7: Emit metrics
    try:
        vm = get_vm_client()
        vm.write_certificate_duration(pr_id, duration_ms)
    except Exception:
        pass

    logger.info(
        "Certificate generated cert_id=%s risk=%s duration_ms=%d",
        cert_id, risk_level, duration_ms,
    )
    return cert
